version: "3.9"
services:
  restaurant-db:
    image: postgres:latest
    container_name: restaurant-db
    ports:
      - 8289:8080
      - 5432:5432
    volumes:
      - "restaurant-db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
volumes:
  restaurant-db: